name: deploy-container

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'ticketing-microfrontend/container/**'

defaults:
  run:
    working-directory: ticketing-microfrontend/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: bpm run build

      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{ secretes.AWS_S3_BUCKET_NAME }}/container/latest
        end:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
